const dotenv = require('dotenv');
dotenv.config();

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const connectDB = require('./config/db');
const User = require('./models/User');
const Product = require('./models/Product');
const Order = require('./models/Order');

const users = [
  {
    name: 'Admin User',
    email: 'admin@gadgethub.com',
    password: 'admin123',
    role: 'admin',
  },
  {
    name: 'John Doe',
    email: 'john@gadgethub.com',
    password: 'user123',
    role: 'user',
  },
];

const products = [
  // ===== MOBILE (8) =====
  {
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Mobile',
    price: 119999,
    originalPrice: 134999,
    stock: 25,
    specs: { ram: '12GB', storage: '256GB', processor: 'Snapdragon 8 Gen 3', battery: '5000mAh', display: '6.8" QHD+ AMOLED', os: 'Android 14' },
    rating: 4.8, numReviews: 245,
    images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600'],
    description: 'The ultimate Galaxy experience with S Pen, titanium frame, and AI-powered camera system with 200MP sensor.',
    featured: true,
  },
  {
    name: 'iPhone 15 Pro Max',
    brand: 'Apple',
    category: 'Mobile',
    price: 159999,
    originalPrice: 169999,
    stock: 30,
    specs: { ram: '8GB', storage: '256GB', processor: 'A17 Pro', battery: '4441mAh', display: '6.7" Super Retina XDR', os: 'iOS 17' },
    rating: 4.9, numReviews: 512,
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600'],
    description: 'Forged in titanium. Featuring the A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
    featured: true,
  },
  {
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: 'Mobile',
    price: 89999,
    originalPrice: 106999,
    stock: 18,
    specs: { ram: '12GB', storage: '128GB', processor: 'Google Tensor G3', battery: '5050mAh', display: '6.7" QHD+ LTPO OLED', os: 'Android 14' },
    rating: 4.6, numReviews: 189,
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600'],
    description: 'The best of Google AI in a smartphone. Magic Eraser, Photo Unblur, and 7 years of OS updates.',
    featured: true,
  },
  {
    name: 'OnePlus 12',
    brand: 'OnePlus',
    category: 'Mobile',
    price: 64999,
    originalPrice: 69999,
    stock: 35,
    specs: { ram: '12GB', storage: '256GB', processor: 'Snapdragon 8 Gen 3', battery: '5400mAh', display: '6.82" QHD+ AMOLED', os: 'Android 14' },
    rating: 4.5, numReviews: 167,
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600'],
    description: 'Flagship killer with Hasselblad camera, 100W SUPERVOOC charging, and stunning display.',
    featured: false,
  },
  {
    name: 'Xiaomi 14 Pro',
    brand: 'Xiaomi',
    category: 'Mobile',
    price: 54999,
    originalPrice: 59999,
    stock: 40,
    specs: { ram: '12GB', storage: '256GB', processor: 'Snapdragon 8 Gen 3', battery: '4880mAh', display: '6.73" QHD+ AMOLED', os: 'Android 14' },
    rating: 4.4, numReviews: 134,
    images: ['https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600'],
    description: 'Leica optics meet powerful performance. Premium build with ceramic back and 120W HyperCharge.',
    featured: false,
  },
  {
    name: 'Samsung Galaxy A55 5G',
    brand: 'Samsung',
    category: 'Mobile',
    price: 29999,
    originalPrice: 34999,
    stock: 50,
    specs: { ram: '8GB', storage: '128GB', processor: 'Exynos 1480', battery: '5000mAh', display: '6.6" FHD+ Super AMOLED', os: 'Android 14' },
    rating: 4.3, numReviews: 98,
    images: ['https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600'],
    description: 'Premium mid-range with flagship-level display, IP67 water resistance, and Samsung Knox security.',
    featured: false,
  },
  {
    name: 'Nothing Phone (2)',
    brand: 'Nothing',
    category: 'Mobile',
    price: 44999,
    originalPrice: 49999,
    stock: 20,
    specs: { ram: '12GB', storage: '256GB', processor: 'Snapdragon 8+ Gen 1', battery: '4700mAh', display: '6.7" FHD+ LTPO OLED', os: 'Android 14' },
    rating: 4.3, numReviews: 76,
    images: ['https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=600'],
    description: 'Iconic Glyph Interface with unique LED notification system. Clean Nothing OS experience.',
    featured: false,
  },
  {
    name: 'Realme GT 5 Pro',
    brand: 'Realme',
    category: 'Mobile',
    price: 37999,
    originalPrice: 42999,
    stock: 30,
    specs: { ram: '8GB', storage: '128GB', processor: 'Snapdragon 8 Gen 3', battery: '5400mAh', display: '6.78" QHD+ AMOLED', os: 'Android 14' },
    rating: 4.2, numReviews: 55,
    images: ['https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=600'],
    description: 'Flagship performance at mid-range price. Sony IMX890 camera and 100W SuperVOOC charge.',
    featured: false,
  },
  // ===== LAPTOP (8) =====
  {
    name: 'MacBook Pro 16" M3 Max',
    brand: 'Apple',
    category: 'Laptop',
    price: 349999,
    originalPrice: 399999,
    stock: 10,
    specs: { ram: '36GB', storage: '1TB', processor: 'Apple M3 Max', battery: '22 hours', display: '16.2" Liquid Retina XDR', os: 'macOS Sonoma' },
    rating: 4.9, numReviews: 198,
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600'],
    description: 'The most powerful MacBook ever. M3 Max chip delivers extraordinary performance for demanding workflows.',
    featured: true,
  },
  {
    name: 'Dell XPS 15',
    brand: 'Dell',
    category: 'Laptop',
    price: 189999,
    originalPrice: 209999,
    stock: 15,
    specs: { ram: '16GB', storage: '512GB', processor: 'Intel Core i7-13700H', battery: '13 hours', display: '15.6" 3.5K OLED', os: 'Windows 11' },
    rating: 4.6, numReviews: 156,
    images: ['https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=600'],
    description: 'InfinityEdge OLED display with stunning colors. Premium aluminum build with edge-to-edge keyboard.',
    featured: true,
  },
  {
    name: 'ASUS ROG Strix G16',
    brand: 'ASUS',
    category: 'Laptop',
    price: 159999,
    originalPrice: 179999,
    stock: 12,
    specs: { ram: '16GB', storage: '1TB', processor: 'Intel Core i9-13980HX', battery: '8 hours', display: '16" QHD+ 240Hz', os: 'Windows 11' },
    rating: 4.7, numReviews: 134,
    images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600'],
    description: 'Ultimate gaming laptop with RTX 4070 graphics, 240Hz display, and intelligent cooling system.',
    featured: true,
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Gen 11',
    brand: 'Lenovo',
    category: 'Laptop',
    price: 169999,
    originalPrice: 189999,
    stock: 18,
    specs: { ram: '16GB', storage: '512GB', processor: 'Intel Core i7-1365U', battery: '15 hours', display: '14" 2.8K OLED', os: 'Windows 11 Pro' },
    rating: 4.7, numReviews: 112,
    images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600'],
    description: 'The gold standard of business laptops. Ultra-light, MIL-STD tested, with legendary ThinkPad keyboard.',
    featured: false,
  },
  {
    name: 'HP Spectre x360 14',
    brand: 'HP',
    category: 'Laptop',
    price: 149999,
    originalPrice: 164999,
    stock: 14,
    specs: { ram: '16GB', storage: '512GB', processor: 'Intel Core i7-1355U', battery: '17 hours', display: '14" 2.8K OLED Touch', os: 'Windows 11' },
    rating: 4.5, numReviews: 89,
    images: ['https://images.unsplash.com/photo-1544731612-de7f96afe55f?w=600'],
    description: '2-in-1 convertible with gem-cut design. OLED touchscreen, stylus support, and premium craftsmanship.',
    featured: false,
  },
  {
    name: 'MacBook Air 15" M3',
    brand: 'Apple',
    category: 'Laptop',
    price: 154999,
    originalPrice: 164999,
    stock: 22,
    specs: { ram: '16GB', storage: '256GB', processor: 'Apple M3', battery: '18 hours', display: '15.3" Liquid Retina', os: 'macOS Sonoma' },
    rating: 4.8, numReviews: 201,
    images: ['https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600'],
    description: 'Impossibly thin. Incredibly powerful. All-day battery. The 15-inch MacBook Air with M3 chip.',
    featured: false,
  },
  {
    name: 'Acer Nitro V Gaming Laptop',
    brand: 'Acer',
    category: 'Laptop',
    price: 79999,
    originalPrice: 94999,
    stock: 28,
    specs: { ram: '16GB', storage: '512GB', processor: 'Intel Core i5-13420H', battery: '8 hours', display: '15.6" FHD 144Hz', os: 'Windows 11' },
    rating: 4.2, numReviews: 67,
    images: ['https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600'],
    description: 'Budget gaming powerhouse with RTX 4050, 144Hz display, and dual-fan cooling at an unbeatable price.',
    featured: false,
  },
  {
    name: 'Microsoft Surface Laptop 5',
    brand: 'Microsoft',
    category: 'Laptop',
    price: 129999,
    originalPrice: 139999,
    stock: 16,
    specs: { ram: '16GB', storage: '512GB', processor: 'Intel Core i7-1255U', battery: '18 hours', display: '13.5" PixelSense Touch', os: 'Windows 11' },
    rating: 4.4, numReviews: 78,
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600'],
    description: 'Sleek and stylish with premium Alcantara keyboard. PixelSense touchscreen and all-day battery life.',
    featured: false,
  },
  // ===== HEADPHONES (5) =====
  {
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'Headphones',
    price: 29999,
    originalPrice: 34999,
    stock: 45,
    specs: { processor: '2 Processors (V1 + QN1)', battery: '30 hours', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.8, numReviews: 320,
    images: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600'],
    description: 'Industry-leading noise cancellation with Auto NC Optimizer. Crystal-clear hands-free calling and 30-hour battery.',
    featured: true,
  },
  {
    name: 'Apple AirPods Pro (2nd Gen)',
    brand: 'Apple',
    category: 'Headphones',
    price: 24999,
    originalPrice: 26999,
    stock: 60,
    specs: { processor: 'Apple H2 Chip', battery: '6h + 30h case', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.7, numReviews: 445,
    images: ['https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600'],
    description: 'Active Noise Cancellation up to 2x more effective. Adaptive Audio and Personalized Spatial Audio.',
    featured: true,
  },
  {
    name: 'Bose QuietComfort Ultra',
    brand: 'Bose',
    category: 'Headphones',
    price: 34999,
    originalPrice: 39999,
    stock: 20,
    specs: { processor: 'Bose CustomTune', battery: '24 hours', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.7, numReviews: 178,
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600'],
    description: 'Immersive Spatial Audio with world-class noise cancellation. Luxurious comfort for all-day wear.',
    featured: false,
  },
  {
    name: 'JBL Tune 770NC',
    brand: 'JBL',
    category: 'Headphones',
    price: 7999,
    originalPrice: 9999,
    stock: 80,
    specs: { processor: 'JBL Pure Bass', battery: '44 hours', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.2, numReviews: 210,
    images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600'],
    description: 'Wireless over-ear headphones with adaptive noise cancelling and legendary JBL Pure Bass sound.',
    featured: false,
  },
  {
    name: 'Samsung Galaxy Buds FE',
    brand: 'Samsung',
    category: 'Headphones',
    price: 6999,
    originalPrice: 8499,
    stock: 55,
    specs: { processor: 'AKG Sound', battery: '6h + 21h case', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.1, numReviews: 132,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=600'],
    description: 'AKG-tuned sound with Active Noise Cancellation. Comfortable fit and seamless Galaxy ecosystem integration.',
    featured: false,
  },
  // ===== SMARTWATCH (5) =====
  {
    name: 'Apple Watch Ultra 2',
    brand: 'Apple',
    category: 'Smartwatch',
    price: 89999,
    originalPrice: 99999,
    stock: 15,
    specs: { processor: 'S9 SiP', battery: '36 hours', display: '49mm Always-On Retina', ram: 'N/A', storage: '64GB', os: 'watchOS 10' },
    rating: 4.8, numReviews: 145,
    images: ['https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600'],
    description: 'The most rugged and capable Apple Watch. Titanium case, precision dual-frequency GPS, and depth gauge.',
    featured: true,
  },
  {
    name: 'Samsung Galaxy Watch 6 Classic',
    brand: 'Samsung',
    category: 'Smartwatch',
    price: 34999,
    originalPrice: 39999,
    stock: 25,
    specs: { processor: 'Exynos W930', battery: '40 hours', display: '1.47" Super AMOLED', ram: '2GB', storage: '16GB', os: 'Wear OS 4' },
    rating: 4.5, numReviews: 189,
    images: ['https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600'],
    description: 'Iconic rotating bezel with advanced health monitoring. BIA sensor, sleep coaching, and Wear OS.',
    featured: false,
  },
  {
    name: 'Garmin Venu 3',
    brand: 'Garmin',
    category: 'Smartwatch',
    price: 44999,
    originalPrice: 49999,
    stock: 12,
    specs: { processor: 'Garmin Custom', battery: '14 days', display: '1.4" AMOLED', ram: 'N/A', storage: '8GB', os: 'Garmin OS' },
    rating: 4.6, numReviews: 98,
    images: ['https://images.unsplash.com/photo-1508685096489-7a6e0de24870?w=600'],
    description: 'Premium GPS smartwatch with up to 14 days battery life, Body Battery energy monitoring, and sleep coach.',
    featured: false,
  },
  {
    name: 'Amazfit GTR 4',
    brand: 'Amazfit',
    category: 'Smartwatch',
    price: 14999,
    originalPrice: 17999,
    stock: 40,
    specs: { processor: 'Huami Custom', battery: '14 days', display: '1.43" AMOLED', ram: 'N/A', storage: '4GB', os: 'Zepp OS' },
    rating: 4.3, numReviews: 234,
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600'],
    description: 'Ultra-long battery life with premium AMOLED display. 150+ sports modes and comprehensive health tracking.',
    featured: false,
  },
  {
    name: 'Noise ColorFit Pro 5',
    brand: 'Noise',
    category: 'Smartwatch',
    price: 3999,
    originalPrice: 5999,
    stock: 100,
    specs: { processor: 'Noise Custom', battery: '7 days', display: '1.85" AMOLED', ram: 'N/A', storage: 'N/A', os: 'Noise OS' },
    rating: 4.0, numReviews: 567,
    images: ['https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600'],
    description: 'Budget-friendly smartwatch with AMOLED display, Bluetooth calling, and 100+ watch faces.',
    featured: false,
  },
  // ===== ACCESSORIES (6) =====
  {
    name: 'Samsung 980 PRO 1TB NVMe SSD',
    brand: 'Samsung',
    category: 'Accessories',
    price: 9999,
    originalPrice: 14999,
    stock: 70,
    specs: { processor: 'Samsung Elpis Controller', battery: 'N/A', display: 'N/A', ram: '1GB DRAM', storage: '1TB NVMe', os: 'N/A' },
    rating: 4.8, numReviews: 890,
    images: ['https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600'],
    description: 'Blazing-fast NVMe SSD with 7000MB/s read speeds. PCIe 4.0, ideal for gaming and creative professionals.',
    featured: false,
  },
  {
    name: 'Logitech MX Master 3S',
    brand: 'Logitech',
    category: 'Accessories',
    price: 8999,
    originalPrice: 10999,
    stock: 45,
    specs: { processor: 'Darkfield 8000 DPI', battery: '70 days', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'Multi-OS' },
    rating: 4.7, numReviews: 456,
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600'],
    description: 'The ultimate ergonomic mouse. MagSpeed scroll, quiet clicks, USB-C, and multi-device connectivity.',
    featured: true,
  },
  {
    name: 'Anker 737 Power Bank 24000mAh',
    brand: 'Anker',
    category: 'Accessories',
    price: 7999,
    originalPrice: 9999,
    stock: 55,
    specs: { processor: 'GaN Technology', battery: '24000mAh', display: 'LED Display', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.6, numReviews: 312,
    images: ['https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600'],
    description: '140W total output with smart digital display. Charge laptop and phone simultaneously with blazing speed.',
    featured: false,
  },
  {
    name: 'Keychron K8 Pro Mechanical Keyboard',
    brand: 'Keychron',
    category: 'Accessories',
    price: 12999,
    originalPrice: 14999,
    stock: 30,
    specs: { processor: 'Broadcom BT 5.1', battery: '4000mAh', display: 'RGB Backlight', ram: 'N/A', storage: 'N/A', os: 'Multi-OS' },
    rating: 4.5, numReviews: 189,
    images: ['https://images.unsplash.com/photo-1595225476474-87563907a212?w=600'],
    description: 'TKL wireless mechanical keyboard with hot-swappable switches. QMK/VIA support, Mac & Windows compatible.',
    featured: false,
  },
  {
    name: 'Apple 20W USB-C Power Adapter',
    brand: 'Apple',
    category: 'Accessories',
    price: 1999,
    originalPrice: 2499,
    stock: 200,
    specs: { processor: 'N/A', battery: 'N/A', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.4, numReviews: 1200,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600'],
    description: 'Fast charge your iPhone or iPad. Compact 20W USB-C adapter with optimized charging efficiency.',
    featured: false,
  },
  {
    name: 'Sony WF-1000XM5 Earbuds',
    brand: 'Sony',
    category: 'Accessories',
    price: 19999,
    originalPrice: 24999,
    stock: 35,
    specs: { processor: 'V2 + QN2e', battery: '8h + 24h case', display: 'N/A', ram: 'N/A', storage: 'N/A', os: 'N/A' },
    rating: 4.7, numReviews: 267,
    images: ['https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=600'],
    description: 'The best noise cancelling earbuds. Smallest and lightest design with exceptional LDAC Hi-Res audio.',
    featured: false,
  },
];

const seedDB = async () => {
  try {
    await connectDB();
    console.log('🗑️  Clearing existing data...');
    await User.deleteMany({});
    await Product.deleteMany({});
    await Order.deleteMany({});

    console.log('👤 Creating users...');
    const salt = await bcrypt.genSalt(10);
    const seededUsers = [];
    for (const u of users) {
      const hashedPassword = await bcrypt.hash(u.password, salt);
      const user = await User.create({ ...u, password: hashedPassword });
      seededUsers.push(user);
    }

    console.log('📦 Creating products...');
    await Product.insertMany(products);

    console.log('\n✅ Database seeded successfully!');
    console.log(`   👤 Users: ${seededUsers.length}`);
    console.log(`   📦 Products: ${products.length}`);
    console.log('\n📋 Login Credentials:');
    console.log('   Admin: admin@gadgethub.com / admin123');
    console.log('   User:  john@gadgethub.com / user123');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seed Error:', error.message);
    process.exit(1);
  }
};

seedDB();
